/*********************************************************************
*                                                                    *
*                SEGGER Microcontroller GmbH & Co. KG                *
*        Solutions for real time microcontroller applications        *
*                                                                    *
**********************************************************************
*                                                                    *
* C-file generated by:                                               *
*                                                                    *
*        GUI_Builder for emWin version 5.32                          *
*        Compiled Oct  8 2015, 11:59:02                              *
*        (c) 2015 Segger Microcontroller GmbH & Co. KG               *
*                                                                    *
**********************************************************************
*                                                                    *
*        Internet: www.segger.com  Support: support@segger.com       *
*                                                                    *
**********************************************************************
*/


#include "DIALOG.h"
#include "stm32f4xx_hal.h"

extern uint8_t state;

#define ID_WINDOW_0  (GUI_ID_USER + 0x00)
#define ID_HEADER_0  (GUI_ID_USER + 0x01)
#define ID_EDIT_TEXT  (GUI_ID_USER + 0x02)
#define ID_BUTTON_Q  (GUI_ID_USER + 0x03)
#define ID_BUTTON_W  (GUI_ID_USER + 0x04)
#define ID_BUTTON_E  (GUI_ID_USER + 0x05)
#define ID_BUTTON_R  (GUI_ID_USER + 0x06)
#define ID_BUTTON_T  (GUI_ID_USER + 0x07)
#define ID_BUTTON_Y  (GUI_ID_USER + 0x08)
#define ID_BUTTON_U  (GUI_ID_USER + 0x09)
#define ID_BUTTON_I  (GUI_ID_USER + 0x0A)
#define ID_BUTTON_O  (GUI_ID_USER + 0x0B)
#define ID_BUTTON_P  (GUI_ID_USER + 0x0C)
#define ID_BUTTON_A  (GUI_ID_USER + 0x0D)
#define ID_BUTTON_S  (GUI_ID_USER + 0x0E)
#define ID_BUTTON_D  (GUI_ID_USER + 0x0F)
#define ID_BUTTON_F  (GUI_ID_USER + 0x10)
#define ID_BUTTON_G  (GUI_ID_USER + 0x11)
#define ID_BUTTON_H  (GUI_ID_USER + 0x12)
#define ID_BUTTON_J  (GUI_ID_USER + 0x13)
#define ID_BUTTON_K  (GUI_ID_USER + 0x14)
#define ID_BUTTON_L  (GUI_ID_USER + 0x15)
#define ID_BUTTON_SHIFT  (GUI_ID_USER + 0x16)
#define ID_BUTTON_Z  (GUI_ID_USER + 0x17)
#define ID_BUTTON_X  (GUI_ID_USER + 0x18)
#define ID_BUTTON_C  (GUI_ID_USER + 0x19)
#define ID_BUTTON_V  (GUI_ID_USER + 0x1A)
#define ID_BUTTON_B  (GUI_ID_USER + 0x1B)
#define ID_BUTTON_N  (GUI_ID_USER + 0x1C)
#define ID_BUTTON_ERASE  (GUI_ID_USER + 0x1E)
#define ID_BUTTON_CANCEL  (GUI_ID_USER + 0x1F)
#define ID_BUTTON_123  (GUI_ID_USER + 0x20)
#define ID_BUTTON_DONE  (GUI_ID_USER + 0x21)
#define ID_BUTTON_SPACE  (GUI_ID_USER + 0x22)

static GUI_CONST_STORAGE unsigned char back_space_img[] =
{
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x11, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x01, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x00,
    0x01, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x00,
    0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x00,
    0x01, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x00,
    0x00, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x11, 0x00,
    0x00, 0x00, 0x11, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x01, 0x11, 0x11, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x01, 0x11, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x01, 0x11, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x01, 0x11, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00,
    0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00, 0x00
};

static const GUI_COLOR Colors[] = { 0x000000, 0x000000 };
static const GUI_LOGPALETTE Palette = { 2, 1, Colors };

GUI_CONST_STORAGE GUI_BITMAP back_space2 =
{
    44, // xSize
    16, // ySize
    22, // BytesPerLine
    4, // BitsPerPixel
    back_space_img,  // Pointer to picture data (indices)
    &Palette   // Pointer to palette
};
/*********************************************************************
*
*       _aDialogCreate
*/
static const GUI_WIDGET_CREATE_INFO _aDialogCreate[] =
{
    { WINDOW_CreateIndirect, "Window", ID_WINDOW_0, 0, 0, 480, 272, 0, 0x0, 0 },
    { HEADER_CreateIndirect, "Header", ID_HEADER_0, 0, 0, 480, 50, 0, 0x0, 0 },
    { EDIT_CreateIndirect, "Edit", ID_EDIT_TEXT, 18, 60, 446, 25, 0, 0x64, 0 },
    { BUTTON_CreateIndirect, "1", ID_BUTTON_Q, 10, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "2", ID_BUTTON_W, 57, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "3", ID_BUTTON_E, 104, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "4", ID_BUTTON_R, 152, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "5", ID_BUTTON_T, 200, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "6", ID_BUTTON_Y, 247, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "7", ID_BUTTON_U, 291, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "8", ID_BUTTON_I, 338, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "9", ID_BUTTON_O, 382, 96, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "0", ID_BUTTON_P, 428, 95, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "-", ID_BUTTON_A, 33, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "/", ID_BUTTON_S, 83, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, ":", ID_BUTTON_D, 129, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, ";", ID_BUTTON_F, 180, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "'", ID_BUTTON_B, 275, 182, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, ".com", ID_BUTTON_N, 317, 182, 60, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "(", ID_BUTTON_G, 226, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, ")", ID_BUTTON_H, 273, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "$", ID_BUTTON_J, 316, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "@", ID_BUTTON_K, 362, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "&", ID_BUTTON_L, 405, 140, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SHIFT", ID_BUTTON_SHIFT, 11, 182, 65, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, ".", ID_BUTTON_Z, 83, 182, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, ",", ID_BUTTON_X, 129, 182, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "?", ID_BUTTON_C, 182, 182, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "!", ID_BUTTON_V, 229, 182, 35, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "", ID_BUTTON_ERASE, 400, 182, 60, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "CANCEL", ID_BUTTON_CANCEL, 28, 225, 85, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "ABC", ID_BUTTON_123, 122, 225, 70, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "DONE", ID_BUTTON_DONE, 400, 225, 70, 32, 0, 0x0, 0 },
    { BUTTON_CreateIndirect, "SPACE", ID_BUTTON_SPACE, 200, 225, 190, 32, 0, 0x0, 0 },
};

/*********************************************************************
*
*       _cbDialog
*/
static void _cbDialog(WM_MESSAGE * pMsg)
{
    WM_HWIN hItem;
    int     NCode;
    int     Id;

    switch (pMsg->MsgId)
    {
    case WM_INIT_DIALOG:
        //
        // Initialization of 'Edit'
        //
        hItem = pMsg->hWin;
        WINDOW_SetBkColor(hItem, 0x00FFFFFF);
        BUTTON_SKINFLEX_PROPS Props;
        BUTTON_GetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED);
        Props.aColorFrame[0] = 0xbbbbbb;
        Props.aColorFrame[1] = 0xeeeeee;
        Props.aColorFrame[2] = 0xeeeeee;
        Props.aColorUpper[0] = 0xcfc4d8;
        Props.aColorUpper[1] = 0xdfd4d8;
        Props.aColorLower[0] = 0xdfd4d8;
        Props.aColorLower[1] = 0xdfdfdf;
        Props.Radius = 2;
        BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_ENABLED);
        Props.aColorUpper[0] = 0x48866c;
        //Props.aColorUpper[1] = 0xcccccc;
        //Props.aColorLower[0] = 0xdddddd;
        Props.aColorLower[1] = 0x62b29a;
        BUTTON_SetSkinFlexProps(&Props, BUTTON_SKINFLEX_PI_PRESSED);

        /* Store new skin properties to enabled button */
        hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_TEXT);
        EDIT_SetText(hItem, "123");
        EDIT_SetFont(hItem, GUI_FONT_20_1);
        EDIT_SetTextAlign(hItem, GUI_TA_LEFT | GUI_TA_VCENTER);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_ERASE);
        BUTTON_SetBitmapEx(hItem, 0,  &back_space2, 10, 8);

        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Q);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_W);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_E);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_R);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_T);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Y);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_U);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_I);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_O);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_P);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_A);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_S);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_D);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_F);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_G);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_H);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_J);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_K);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_L);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SHIFT);
        BUTTON_SetFont(hItem, GUI_FONT_20_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_Z);
        BUTTON_SetFont(hItem, GUI_FONT_20_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_X);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_C);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_V);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_B);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_N);
        BUTTON_SetFont(hItem, GUI_FONT_20B_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_CANCEL);
        BUTTON_SetFont(hItem, GUI_FONT_20_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_123);
        BUTTON_SetFont(hItem, GUI_FONT_20_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_DONE);
        BUTTON_SetFont(hItem, GUI_FONT_20_1);
        //
        // Initialization of 'Button'
        //
        hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_SPACE);
        BUTTON_SetFont(hItem, GUI_FONT_20_1);
        break;
    case WM_NOTIFY_PARENT:
        Id    = WM_GetId(pMsg->hWinSrc);
        NCode = pMsg->Data.v;
        char buf[10], txtBuffer[50];
        sprintf(buf,"ID=%d, Ncode=%d, C=%d", Id, NCode, GUI_COUNTOF(_aDialogCreate));
        switch(NCode)
        {
        case WM_NOTIFICATION_RELEASED:
            //GUI_ErrorOut(buf);
            if ((Id >= GUI_ID_USER) && (Id <= (GUI_ID_USER + GUI_COUNTOF(_aDialogCreate) - 1)))
            {
                char acBuffer[10];
                BUTTON_GetText(pMsg->hWinSrc, acBuffer, sizeof(acBuffer));
                //GUI_ErrorOut(acBuffer);
                if (strcmp("SHIFT", acBuffer) == 0)
                {
                    //GUI_ErrorOut("SHIFT");
                   // hItem = WM_GetDialogItem(pMsg->hWin, ID_BUTTON_M);
                    //BUTTON_SetText(hItem, "M");
                }
                else if (strcmp("ERASE", acBuffer) == 0)
                {
                    GUI_ErrorOut("ERASE");
                }
                else if (strcmp("ABC", acBuffer) == 0)
                {
                    GUI_ErrorOut("123");
                    state = 8;
                    break;
                }
                else
                {
                    hItem = WM_GetDialogItem(pMsg->hWin, ID_EDIT_TEXT);
                    EDIT_GetText(hItem, txtBuffer, 50);
                    //GUI_ErrorOut(txtBuffer);
                    EDIT_SetText(hItem, acBuffer);
                }
            }
        }
        break;
    default:
        WM_DefaultProc(pMsg);
        break;
    }
}

/*********************************************************************
*
*       CreateWindow
*/
WM_HWIN CreateNumericKeyboard(void);
WM_HWIN CreateNumericKeyboard(void)
{
    WM_HWIN hWin;

    hWin = GUI_CreateDialogBox(_aDialogCreate, GUI_COUNTOF(_aDialogCreate), _cbDialog, WM_HBKWIN, 0, 0);
    return hWin;
}

/*************************** End of file ****************************/
